// Constants File: defines system-wide domain constants for matching states, events, failures, and config values.

const TRIP_STATUS = {
  PENDING: "PENDING",
  MATCHING: "MATCHING",
  ACCEPTED: "ACCEPTED",
  PICKEDUP: "PICKEDUP",
  DROPPED: "DROPPED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  DIVERGED: "DIVERGED",
  FAILED: "failed"
};

const MATCH_EVENTS = {
  TRIP_REQUEST_ATTEMPT: "trip_request_attempt",
  SOCKET_MESSAGE_SENT: "socket_message_sent",
  DRIVER_TRIP_RESPONSE: "driver_trip_response",
  DRIVER_NOT_CONNECTED: "driver_not_connected",
  TRIP_ALLOCATED: "trip_allocated",
  MATCH_FAILED: "match_failed",
  REMATCH_TRIGGERED: "rematch_triggered"
};

const DRIVER_RESPONSE = {
  ACCEPT: "accept",
  REJECT: "reject",
  TIMEOUT: "timeout",
  ERROR_NO_TRIP: "error_no_trip_details"
};

const CANCEL_BY = {
  DRIVER: "DRIVER",
  PASSENGER: "PASSENGER",
  SYSTEM: "SYSTEM"
};

const TRIP_TIMELINE_STATES = {
  ACCEPTED: "ACCEPTED",
  PICKEDUP: "PICKEDUP",
  DROPPED: "DROPPED",
  COMPLETED: "COMPLETED",
  CANCELLED_BY_DRIVER_BEFORE_PICKUP: "CANCELLED_BY_DRIVER_BEFORE_PICKUP",
  CANCELLED_BY_DRIVER_AFTER_PICKUP: "CANCELLED_BY_DRIVER_AFTER_PICKUP",
  CANCELLED_BY_PASSENGER_BEFORE_PICKUP: "CANCELLED_BY_PASSENGER_BEFORE_PICKUP",
  CANCELLED_BY_PASSENGER_AFTER_PICKUP: "CANCELLED_BY_PASSENGER_AFTER_PICKUP",
  DIVERGED: "DIVERGED"
};

const FAILURE_REASONS = {
  NO_AVAILABLE_DRIVERS: "NoAvailableDrivers",
  MAX_RETRIES_EXCEEDED: "MaxRetriesExceeded",
  TRIP_CANCELLED: "TripCancelledBeforeMatch"
};

const MATCHING_CONFIG = {
  MAX_ATTEMPTS: 3,
  SHORTLIST_SIZE: 5,
  RESPONSE_TIMEOUT_MS: 15000,
  SEARCH_RADIUS_KM: 10,
  MAX_CANCELLATION_RETRIES: 3
};

module.exports = {
  TRIP_STATUS,
  MATCH_EVENTS,
  DRIVER_RESPONSE,
  CANCEL_BY,
  TRIP_TIMELINE_STATES,
  FAILURE_REASONS,
  MATCHING_CONFIG
};
